### ISSUE TITLE
Crashing when clicking on "known hotspots"

### ISSUE THREAD

**Issue by bisam** [BramBonne/privacypolice#33]
I just did a fresh install via f-droid. Every time i cl

**Comment by BramBonne** [comment]
Hi bisam!

Could you provide me with a logcat when the crash occurs?

**Comment by bisam** [comment]
hi,

i filtered the output:

```
I/ActivityManager(  384): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=be.uhasselt.privacypolice/.PreferencesActivity u=0} from pid 677
I/ActivityManager(  384): Start proc be.uhasselt.privacypolice for activity be.uhasselt.privacypolice/.PreferencesActivity: pid=1994 uid=10145 gids={1028}
I/ActivityManager(  384): START {cmp=be.uhasselt.privacypolice/.SSIDManagerActivity u=0} from pid 1994
E/AndroidRuntime( 1994): java.lang.RuntimeException: Unable to start activity ComponentInfo{be.uhasselt.privacypolice/be.uhasselt.privacypolice.SSIDManagerActivity}: java.lang.NullPointerException
E/AndroidRuntime( 1994): 	at be.uhasselt.privacypolice.r.a(Unknown Source)
E/AndroidRuntime( 1994): 	at be.uhasselt.privacypolice.k.<init>(Unknown Source)
E/AndroidRuntime( 1994): 	at be.uhasselt.privacypolice.r.<init>(Unknown Source)
E/AndroidRuntime( 1994): 	at be.uhasselt.privacypolice.SSIDManagerActivity.onCreate(Unknown Source)
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.SSIDManagerActivity
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.PreferencesActivity
W/ActivityManager(  384): Activity pause timeout for ActivityRecord{4134ab98 be.uhasselt.privacypolice/.SSIDManagerActivity}
I/ActivityManager(  384): Process be.uhasselt.privacypolice (pid 1994) has died.
I/WindowState(  384): WIN DEATH: Window{4246cbf8 be.uhasselt.privacypolice/be.uhasselt.privacypolice.PreferencesActivity paused=true}
I/WindowManager(  384): WINDOW DIED Window{4246cbf8 be.uhasselt.privacypolice/be.uhasselt.privacypolice.PreferencesActivity paused=true}
I/ActivityManager(  384): Start proc be.uhasselt.privacypolice for broadcast be.uhasselt.privacypolice/.WakelockHandler: pid=3854 uid=10145 gids={1028}
I/ActivityManager(  384): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=be.uhasselt.privacypolice/.PreferencesActivity u=0} from pid 677
I/ActivityManager(  384): START {cmp=be.uhasselt.privacypolice/.SSIDManagerActivity u=0} from pid 3854
E/AndroidRuntime( 3854): java.lang.RuntimeException: Unable to start activity ComponentInfo{be.uhasselt.privacypolice/be.uhasselt.privacypolice.SSIDManagerActivity}: java.lang.NullPointerException
E/AndroidRuntime( 3854): 	at be.uhasselt.privacypolice.r.a(Unknown Source)
E/AndroidRuntime( 3854): 	at be.uhasselt.privacypolice.k.<init>(Unknown Source)
E/AndroidRuntime( 3854): 	at be.uhasselt.privacypolice.r.<init>(Unknown Source)
E/AndroidRuntime( 3854): 	at be.uhasselt.privacypolice.SSIDManagerActivity.onCreate(Unknown Source)
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.SSIDManagerActivity
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.PreferencesActivity
W/ActivityManager(  384): Activity pause timeout for ActivityRecord{41e61df8 be.uhasselt.privacypolice/.SSIDManagerActivity}
I/WindowState(  384): WIN DEATH: Window{414961b8 be.uhasselt.privacypolice/be.uhasselt.privacypolice.PreferencesActivity paused=true}
I/ActivityManager(  384): Process be.uhasselt.privacypolice (pid 3854) has died.
I/ActivityManager(  384): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=be.uhasselt.privacypolice/.PreferencesActivity u=0} from pid 677
I/ActivityManager(  384): Start proc be.uhasselt.privacypolice for activity be.uhasselt.privacypolice/.PreferencesActivity: pid=5561 uid=10145 gids={1028}
I/ActivityManager(  384): START {cmp=be.uhasselt.privacypolice/.SSIDManagerActivity u=0} from pid 5561
E/AndroidRuntime( 5561): java.lang.RuntimeException: Unable to start activity ComponentInfo{be.uhasselt.privacypolice/be.uhasselt.privacypolice.SSIDManagerActivity}: java.lang.NullPointerException
E/AndroidRuntime( 5561): 	at be.uhasselt.privacypolice.r.a(Unknown Source)
E/AndroidRuntime( 5561): 	at be.uhasselt.privacypolice.k.<init>(Unknown Source)
E/AndroidRuntime( 5561): 	at be.uhasselt.privacypolice.r.<init>(Unknown Source)
E/AndroidRuntime( 5561): 	at be.uhasselt.privacypolice.SSIDManagerActivity.onCreate(Unknown Source)
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.SSIDManagerActivity
W/ActivityManager(  384):   Force finishing activity be.uhasselt.privacypolice/.PreferencesActivity
W/ActivityManager(  384): Activity pause timeout for ActivityRecord{413ca650 be.uhasselt.privacypolice/.SSIDManagerActivity}
I/ActivityManager(  384): Process be.uhasselt.privacypolice (pid 5561) has died.
I/WindowState(  384): WIN DEATH: Window{41bf3040 be.uhasselt.privacypolice/be.uhasselt.privacypolice.PreferencesActivity paused=true}
```
